chown -R root:root .
chown www-data:www-data ./application/controllers
chown -R www-data:www-data ./application/controllers/lib
chown -R www-data:www-data ./application/static/images/menu
chown -R www-data:www-data ./backups
chown -R www-data:www-data ./install
chown -R www-data:www-data ./uploads
chown -R www-data:www-data ./logs
chown -R www-data:www-data ./tmp
chown -R www-data:www-data ./user/config

